start: stream_file

stream_file: stream_def+

stream_def: "(" ":stream" NAME stream_field+ ")"

stream_field: inputs
            | domain
            | outputs
            | certified

inputs: ":inputs" var_list
outputs: ":outputs" var_list

domain: ":domain" logical_expr
certified: ":certified" logical_expr

var_list: "(" variable+ ")"

logical_expr: predicate
            | "(" "and" logical_expr+ ")" -> and_expr

predicate: "(" NAME term* ")"

term: variable
    | NAME

variable: VAR

NAME: /[a-zA-Z_][a-zA-Z0-9_-]*/
VAR: /\?[a-zA-Z_][a-zA-Z0-9_-]*/

%import common.WS
%ignore WS
