?start: domain

domain: "(" "define" "(" "domain" NAME ")" domain_body ")"

domain_body: requirements? types? functions? predicates derived* action+

requirements: "(" ":requirements" requirement* ")"
requirement: ":" NAME

types: "(" ":types" type_decl+ ")"
type_decl: NAME+ "-" NAME

functions: "(" ":functions" function_decl* ")"
function_decl: "(" NAME taggable_var* ")"

predicates: "(" ":predicates" predicate_def+ ")"
predicate_def: "(" NAME taggable_var* ")"

derived: "(" ":derived" "(" NAME taggable_var_list ")" formula ")"

action: "(" ":action" NAME parameters precondition effect ")"

parameters: ":parameters" "(" taggable_var+ ")"

precondition: ":precondition" formula
effect: ":effect" formula

?formula: atom
        | "(" "and" formula+ ")" -> conjunction
        | "(" "not" formula ")" -> negation
        | "(" "or" formula+ ")" -> disjunction
        | existential
        | universal
        | implies

existential: "(" "exists" "(" taggable_var_list ")" formula ")"
universal: "(" "forall" "(" taggable_var_list ")" formula ")"
implies: "(" "implies" formula formula ")"

atom: "(" NAME term* ")"

term: group_var | var | NAME

var: "?" NAME
group_var: "&" NAME

taggable_var: group_var | var | typed_var
typed_var: (group_var | var) "-" NAME

taggable_var_list: taggable_var*
var_list: var*


NAME: /[a-zA-Z_][a-zA-Z0-9_-]*/

COMMENT: ";" /[^\n]*/ NEWLINE

%import common.WS
%import common.NEWLINE
%ignore WS
%ignore COMMENT
